### ISSUE TITLE
Can't get use of secrets.yaml to work 

### ISSUE THREAD

**Issue by sddgit** [LordMike/MBW.BlueRiiot2MQTT#63]
I'm sure this is something I'm doing wrong (pretty new to HA), but I can’t get the mqtt username and password to work if I put them in the secrets.yaml file. My config currently looks like this, and it works (I manually added the mqtt username to HA for now):

```
MQTT:  
  Server: 192.168.0.240. 
  Port: 1883
  Username: mqtt
  Password: mqtt
  ClientId: blueriiot2mqtt
BlueRiiot:
  Username: '!secret blueriiot_username'
  Password: '!secret blueriiot_password'
  Language: en
  DiscoveryInterval: '12:00:00'
  UpdateInterval: '01:00:00'
  UpdateIntervalWhenAllDevicesAsleep: '08:00:00'
  ReportUnchangedValues: false
  EnableSchedule: true
HASS:
  DiscoveryPrefix: homeassistant
  TopicPrefix: blueriiot
  EnableHASSDiscovery: true
```

The username and password for the BlueRiiot login works fine in this format. If I change the mqtt username and password so it looks like this:

```
MQTT:  
  Server: 192.168.0.240. 
  Port: 1883
  Username: '!secret blueriiot_mqtt_username'
  Password: '!secret blueriiot_mqtt_password'
  ClientId: blueriiot2mqtt
BlueRiiot:
  Username: '!secret blueriiot_username'
  Password: '!secret blueriiot_password'
  Language: en
  DiscoveryInterval: '12:00:00'
  UpdateInterval: '01:00:00'
  UpdateIntervalWhenAllDevicesAsleep: '08:00:00'
  ReportUnchangedValues: false
  EnableSchedule: true
HASS:
  DiscoveryPrefix: homeassistant
  TopicPrefix: blueriiot
  EnableHASSDiscovery: true
```

with this in secrets.yaml:

```
blueriiot_mqtt_username: xxxxxxx
blueriiot_mqtt_password: xxxxxxx
```

I get mqtt authentication errors. Must be some sort off syntax error I don't understand. Help appreciated!
